name: Deploy to Azure App Service

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # or your preferred Node.js version

      - name: List directory contents
        run: ls -la

      - name: Display package.json content
        run: cat package.json

      - name: Display npm config
        run: npm config list

      - name: Install dependencies
        run: npm install

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'apiserverapp'  # Replace with your App Service name
          slot-name: 'production'

      - name: Start Node.js server
        env:
          WEBSITE_RUN_FROM_PACKAGE: 0
        run: |
          npm start &
          echo "Server started"

      - name: Check server status
        run: |
          sleep 10  # Give the server some time to start
          curl http://localhost:3000 || echo "Server not responding on localhost"
          curl https://apiserverapp.azurewebsites.net || echo "Server not responding on Azure URL"

      - name: Display Azure Web App logs
        run: |
          az webapp log tail --name apiserverapp --resource-group apiserver